# Generated by Django 4.1.2 on 2022-10-25 09:07

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=customer.models.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('black', models.BooleanField(default=False, help_text='0=default, 1=Black')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
