# Generated by Django 4.1.2 on 2022-10-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_user',
            old_name='password',
            new_name='pass1',
        ),
    ]
