# Generated by Django 4.1.2 on 2022-11-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_password_new_user_pass1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
