# Generated by Django 4.1.2 on 2022-11-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_new_user_email_alter_new_user_pass1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_user',
            old_name='pass1',
            new_name='password',
        ),
    ]
